Repository ticket-web-team6/ticket-book, pull requests merged in 2024-07, with the labels that each got.

#2 Feat/#1 crud
  build.gradle.kts
  src/main/kotlin/com/team6/ticketbook/domain/book/controller/BookController.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/dto/BookResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/dto/CreateBookRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/model/Book.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/repository/BookRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/service/BookService.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/controller/AuthController.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/controller/MemberController.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/dto/RegisterRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/dto/UpdateMemberAddressRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/model/Member.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/service/AuthService.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/service/MemberService.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/controller/ShowController.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/dto/CreateShowRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/dto/ShowResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/dto/UpdateShowImageRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/model/Show.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/model/ShowStartTime.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/repository/ShowRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/service/ShowService.kt
Labels: :sparkles: feat

#4 Feat/#3 auth
  build.gradle.kts
  src/main/kotlin/com/team6/ticketbook/domain/book/controller/BookController.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/dto/CreateBookRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/service/BookService.kt
  src/main/kotlin/com/team6/ticketbook/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/team6/ticketbook/domain/exception/InvalidCredentialException.kt
  src/main/kotlin/com/team6/ticketbook/domain/exception/ModelNotFoundException.kt
  src/main/kotlin/com/team6/ticketbook/domain/exception/dto/ErrorResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/controller/AuthController.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/controller/MemberController.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/dto/LoginRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/dto/LoginResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/model/MemberRole.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/service/AuthService.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/service/MemberService.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/controller/ShowController.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/MemberPrincipal.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/PasswordEncoderConfig.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/SecurityConfig.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/jwt/JwtHelper.kt
Labels: :sparkles: feat

#8 Feat/#7 impl show
  build.gradle.kts
  src/main/kotlin/com/team6/ticketbook/domain/show/controller/ShowController.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/service/ShowService.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/SecurityConfig.kt
Labels: :sparkles: feat

#9 Feat/#5 book
  build.gradle.kts
  src/main/kotlin/com/team6/ticketbook/domain/book/dto/BookResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/dto/CreateBookRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/exception/InvalidDateException.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/exception/SeatAlreadyTakenException.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/model/Book.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/repository/BookRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/service/BookService.kt
  src/main/kotlin/com/team6/ticketbook/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/team6/ticketbook/domain/place/dto/PlaceResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/place/model/Place.kt
  src/main/kotlin/com/team6/ticketbook/domain/place/repository/PlaceRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/seat/dto/SeatResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/seat/model/Seat.kt
  src/main/kotlin/com/team6/ticketbook/domain/seat/repository/SeatRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/controller/ShowController.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/dto/CreateShowRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/dto/ShowResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/dto/ShowSearchFilter.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/model/Show.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/repository/ShowRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/service/ShowService.kt
  src/main/kotlin/com/team6/ticketbook/infra/queryDSL/QueryDslConfig.kt
Labels: :sparkles: feat

#10 Feat/#6 Implement Auth/Member Service tests
  src/main/kotlin/com/team6/ticketbook/domain/member/exception/EmailAlreadyOccupiedException.kt
  src/main/kotlin/com/team6/ticketbook/domain/member/service/AuthService.kt
  src/test/kotlin/com/team6/ticketbook/TicketbookApplicationTests.kt
  src/test/kotlin/com/team6/ticketbook/domain/member/AuthServiceTest.kt
  src/test/kotlin/com/team6/ticketbook/domain/member/MemberServiceTest.kt
Labels: :white_check_mark: test

#13 Test/#12 Implement test for concurrency control
  build.gradle.kts
  src/main/kotlin/com/team6/ticketbook/domain/book/dto/CreateBookRequest.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/repository/BookRepository.kt
  src/test/kotlin/com/team6/ticketbook/domain/book/RaceConditionTest.kt
Labels: :white_check_mark: test

#16 Feat/#15 Implement Redis Lock
  build.gradle.kts
  src/main/kotlin/com/team6/ticketbook/domain/book/controller/BookController.kt
  src/main/kotlin/com/team6/ticketbook/domain/book/service/BookService.kt
  src/main/kotlin/com/team6/ticketbook/infra/redis/LettuceConfig.kt
  src/main/kotlin/com/team6/ticketbook/infra/redis/RedisLock.kt
Labels: :sparkles: feat

#18 feat/#11-Impl-Searchs
  src/main/kotlin/com/team6/ticketbook/domain/place/dto/PlaceResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/controller/SearchController.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/controller/ShowController.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/dto/ShowResponse.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/dto/TopSearchKeyword.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/repository/ShowRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/service/SearchService.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/service/ShowService.kt
  src/main/kotlin/com/team6/ticketbook/infra/redis/LettuceConfig.kt
  src/main/kotlin/com/team6/ticketbook/infra/security/SecurityConfig.kt
Labels: :sparkles: feat

#20 Feat/#19 Refactor Search API
  src/main/kotlin/com/team6/ticketbook/domain/book/service/BookService.kt
  src/main/kotlin/com/team6/ticketbook/domain/lock/service/LockService.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/repository/ShowRepository.kt
  src/main/kotlin/com/team6/ticketbook/domain/show/service/SearchService.kt
Labels: :recycle: refactor
